/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz1;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static quiz1.Quiz_Form_database2.num1;

/**
 *
 * @author Administrator
 */
public class Login_page1 extends javax.swing.JFrame {

    static String num2=null;
    
    
    
    public Login_page1() {
        initComponents();
    }
    
    public void file1(String content2){
    
        try{
        
            File file = new File("C:/Users/SUJATA/Documents/NetBeansProjects/NewPage/src/quiz1/mylogin.txt");
            
            if(!file.exists()){
            file.createNewFile();
            }
               
            //here false is to overwrite the content of file
            FileWriter fw = new FileWriter(file);
            
            //BufferedWriter writer give better performance
            
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(content2);
            
            //closing BufferedWriter Stream
            bw.close();
        }
        catch(Exception e){System.out.println("Erororo"+e.getMessage());}
    }
    
    public void user_id_file(String content8){
    
        try{
        
            File file = new File("C:/Users/SUJATA/Documents/NetBeansProjects/NewPage/src/quiz1/user_id_file.txt");
            
            if(!file.exists()){
            file.createNewFile();
            }
               
            //here false is to overwrite the content of file
            FileWriter fw = new FileWriter(file);
            
            //BufferedWriter writer give better performance
            
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(content8);
            
            //closing BufferedWriter Stream
            bw.close();
        }
        catch(Exception e){System.out.println("Erororo"+e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        reset1 = new javax.swing.JButton();
        text2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAlignmentX(100);
        jPanel1.setAlignmentY(100);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-enter-100.png"))); // NOI18N
        jLabel1.setText("LOGIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 290, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 261, 205, 54));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 385, 202, -1));

        text1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        jPanel2.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 330, 60));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 199, 57));

        reset1.setBackground(new java.awt.Color(255, 204, 0));
        reset1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reset1.setText("register");
        reset1.setBorder(null);
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        jPanel2.add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 199, 57));

        text2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 340, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 110, 50));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(255, 255, 255), null, null));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 890, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userValue=text1.getText();
        String passValue=text2.getText();
        
        String a="";
        String b="";
        
        if(userValue.equals("admin") && passValue.equals("namita")){
            
            this.setVisible(false);
            admin kk = new admin();
            kk.setVisible(true);
            
     
            }
         
        else if(passValue.equals(a) && userValue.equals(a)){
               JOptionPane.showMessageDialog(this,"Enter username and password");
         
        }    
        else if(userValue.equals(a)){
               JOptionPane.showMessageDialog(this,"Enter username");
         
        }    
         else   if (passValue.equals(a)) {    
                JOptionPane.showMessageDialog(this,"Enter Password");
            }
         else{
          
        
        try{  
Class.forName("com.mysql.cj.jdbc.Driver");  
Connection con;
    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc","root","12345");
//here sonoo is database name, root is username and password  
Statement stmt=(Statement) con.createStatement();  
ResultSet rs=(ResultSet) stmt.executeQuery("select * from uselogin where username='"+userValue+"' and password='"+passValue+"';");  

 if(rs.next())
            {
            //create a instance of NewPage
              
                 num2 = rs.getString(1);  
                 System.out.println(num2);
                progressbar page = new progressbar();
                
                //make page visible to user                
                page.setVisible(true);
                this.setVisible(false);
            
            
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please enter valid username & password");    
            }       

        con.close();  
}catch( HeadlessException | ClassNotFoundException | SQLException e)
{ 
    System.out.println(e);
}
        
        file1(userValue);
        user_id_file(num2);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_text1ActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        registerform g1 = new registerform();
        this.setVisible(false);
        g1.setVisible(true);
    }//GEN-LAST:event_reset1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            dispose();
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login_page1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton reset1;
    private javax.swing.JTextField text1;
    private javax.swing.JPasswordField text2;
    // End of variables declaration//GEN-END:variables
}
