/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static quiz1.Quiz_Form_database2.subject1;
import static quiz1.Quiz_Form_database2.subject99;

/**
 *
 * @author SUJATA
 */
public class total extends javax.swing.JFrame {

    static String totalsub;
    static String totaluser;
    int totall;
    
    public total() {
        initComponents();
        file2();
        file5();
    }

      public void file5(){
    
        try{
        
            File f1 = new File("C:/Users/SUJATA/Documents/NetBeansProjects/NewPage/src/quiz1/mylogin.txt");
            BufferedReader br = new BufferedReader(new FileReader(f1));
            String str;
            while((str = br.readLine()) != null){
                subject99 = str;
                
            }
            br.close();
            totaluser = subject99;
            System.out.println(totaluser);
        }
        catch(IOException er){
            System.out.println("ErrrrrO"+er.getMessage());
        }
    
    }
    public void file2() {

        try {
            File fl = new File("C:/Users/SUJATA/Documents/NetBeansProjects/NewPage/src/quiz1/myfile.txt");
            BufferedReader br = new BufferedReader(new FileReader(fl));
            String str;
            while ((str = br.readLine()) != null) {
                subject1 = str;
            }
            br.close();
            totalsub = subject1;
            System.out.println(totalsub);
          
        } catch (IOException e) {
            
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        g1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        g1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g1.setText("DO Want to Save Test ?");

        btn1.setText("YES");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("NO");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btn1)
                .addGap(111, 111, 111)
                .addComponent(btn2)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2))
                .addGap(128, 128, 128))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        gettotal();
        insertingT();
        
      
        Form_Menu jj = new Form_Menu();
                this.setVisible(false);
                jj.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed

            
     
           deleting();  
        Form_Menu jj = new Form_Menu();
                this.setVisible(false);
                jj.setVisible(true);
        
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new total().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JLabel g1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void gettotal() {
        
        try{
    
            Class.forName("com.mysql.cj.jdbc.Driver");          
            Connection con4 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc", "root", "12345");
            Statement stmt5 = (Statement) con4.createStatement();
            ResultSet rs1 = stmt5.executeQuery("select sum(marks) from response where subject='"+totalsub+"';");

            rs1.next();
            
            totall=rs1.getInt(1);
            System.out.println("total count of marks"+totall); 
            }
        catch(ClassNotFoundException | SQLException pps){
            System.out.println("terror "+pps.getMessage());
        }
        
    }

    private void insertingT() 
    {
    
           try
        {
            
            Connection con4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc","root","12345");
            PreparedStatement psg = con4.prepareStatement("insert into record(rename2,resubject,retotal) values(?,?,?);");
            
            psg.setString(1, totaluser);
            psg.setString(2, totalsub);         
            psg.setInt(3,totall);
            int row = psg.executeUpdate();
            if(row>0){
                  System.out.println("total saved"); 
            }
          
   
        }
        catch(SQLException r)
        {
            System.out.println("Record Not inserted "+r.getMessage());
        }
    
    }
    
    private void deleting(){
    
           try {
            Connection con2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc", "root", "12345");
            Statement stm = (Statement) con2.createStatement();
            stm.executeUpdate("truncate table record;");
            System.out.println("delete");
           
            stm.close();
            con2.close();
        } catch (SQLException ex) {
            System.out.println("General Info Error"+ex.getMessage());
        }
    }
    
    
}
